package com.mekromn.bubble

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.net.TrafficStats
import android.os.BatteryManager
import android.os.Debug
import android.os.Environment
import android.os.Handler
import android.os.Looper
import android.os.PowerManager
import android.os.Process
import android.os.SystemClock
import android.provider.MediaStore
import android.view.Choreographer
import android.view.HapticFeedbackConstants
import android.view.MotionEvent
import android.view.SurfaceView
import android.view.View
import android.widget.Toast
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.Random
import kotlin.math.ceil
import kotlin.math.max
import kotlin.math.min

/**
 * Physical, same-process renderer A/B recorder.
 *
 * Measurement is deliberately dormant unless the user starts a run. Both renderer arms keep
 * Build-140 UNBUFFERED_140 page input. Blocks are counterbalanced by pair and begin only on a fresh
 * physical ACTION_DOWN after the selected real floating renderer is live and has Android window
 * focus. No synthetic page input is generated by this class.
 *
 * Scope warnings are intentional: Choreographer cadence is Bubble's app/UI scheduler cadence, not
 * Gecko/SurfaceFlinger presentation FPS; input->Choreographer is not touch-to-photon; process CPU,
 * PSS and allocation counters describe Bubble's app process, not every Gecko/system process.
 */
internal object RendererBenchmark {
    private const val TARGET_BLOCK_NS = 8_000_000_000L
    private const val HARD_BLOCK_NS = 25_000_000_000L
    private const val BETWEEN_BLOCK_MS = 1900L
    private const val READY_SETTLE_MS = 450L
    private const val READY_TIMEOUT_MS = 20_000L
    private const val HIST_BINS = 512

    private val main = Handler(Looper.getMainLooper())
    private var run: RunState? = null
    private var pending: PendingBlock? = null
    private var active: Recorder? = null
    private var frameLoopPosted = false

    private val frameCallback = Choreographer.FrameCallback { frameTimeNanos ->
        frameLoopPosted = false
        val recorder = active
        if (recorder != null && recorder.startedNanos != 0L) recorder.onFrame(frameTimeNanos)
        if (run != null) ensureFrameLoop()
    }

    data class Status(
        val running: Boolean,
        val block: Int,
        val totalBlocks: Int,
        val phase: String,
        val latestSummary: String
    )

    private data class PendingBlock(
        val index: Int,
        val pair: Int,
        val transport: RendererArena.Transport,
        val recorder: Recorder,
        var ready: Boolean = false
    )

    private data class RunState(
        val app: Context,
        val pairs: Int,
        val seed: Long,
        val order: List<RendererArena.Transport>,
        val results: MutableList<BlockResult> = ArrayList(),
        val startedWallMs: Long = System.currentTimeMillis()
    )

    private class Histogram(private val widthNs: Long) {
        private val bins = LongArray(HIST_BINS)
        var count = 0L
            private set
        fun add(valueNs: Long) {
            val value = valueNs.coerceAtLeast(0L)
            val index = min((value / widthNs).toInt(), HIST_BINS - 1)
            bins[index]++
            count++
        }
        fun percentile(q: Double): Double {
            if (count == 0L) return Double.NaN
            val target = max(1L, ceil(count * q.coerceIn(0.0, 1.0)).toLong())
            var total = 0L
            for (i in bins.indices) {
                total += bins[i]
                if (total >= target) return (i + 0.5) * widthNs / 1_000_000.0
            }
            return (HIST_BINS - 0.5) * widthNs / 1_000_000.0
        }
    }

    private data class StartSnapshot(
        val processCpuMs: Long,
        val mainCpuNs: Long,
        val energyNwh: Long,
        val rxBytes: Long,
        val txBytes: Long,
        val relay: LongArray
    )

    private data class EndSnapshot(
        val processCpuMs: Long,
        val mainCpuNs: Long,
        val energyNwh: Long,
        val currentUa: Int,
        val rxBytes: Long,
        val txBytes: Long,
        val pssKb: Long,
        val heapUsedBytes: Long,
        val gcCount: Long,
        val allocatedBytes: Long,
        val thermal: Int,
        val headroom: Float,
        val refreshRate: Float,
        val relay: LongArray
    )

    private class Recorder(
        val index: Int,
        val pair: Int,
        val transport: RendererArena.Transport
    ) {
        val eventAge = Histogram(125_000L)          // 0.125 ms bins
        val handler = Histogram(25_000L)            // 0.025 ms bins
        val sampleSpacing = Histogram(125_000L)     // source-sample spacing
        val uiFrames = Histogram(125_000L)          // Bubble Choreographer cadence
        val inputToUiFrame = Histogram(125_000L)    // NOT presentation latency
        var startedNanos = 0L
        var endedNanos = 0L
        var eventCount = 0L
        var downCount = 0L
        var moveCount = 0L
        var upCount = 0L
        var cancelCount = 0L
        var historyEvents = 0L
        var historySamples = 0L
        var inGesture = false
        var finishRequested = false
        var forcedFinish = false
        var lastSourceSampleNanos = 0L
        var lastFrameNanos = 0L
        var pendingInputNanos = 0L
        var uiFrameCount = 0L
        var uiJankCount = 0L
        var nominalFrameNs = 8_333_333L
        lateinit var start: StartSnapshot
        var targetFinish: Runnable? = null
        var hardFinish: Runnable? = null

        fun begin(app: Context) {
            startedNanos = SystemClock.uptimeNanos()
            nominalFrameNs = currentRefreshRate()?.takeIf { it > 1f }?.let { (1_000_000_000.0 / it).toLong() } ?: 8_333_333L
            start = StartSnapshot(
                Process.getElapsedCpuTime(),
                Debug.threadCpuTimeNanos(),
                energyCounter(app),
                safeUidRx(),
                safeUidTx(),
                relayStats()
            )
            targetFinish = Runnable { requestFinish(this) }.also { main.postDelayed(it, TARGET_BLOCK_NS / 1_000_000L) }
            hardFinish = Runnable {
                if (active === this) {
                    forcedFinish = true
                    if (inGesture) cancel("A gesture stayed active too long; benchmark canceled rather than switching renderers under your finger.")
                    else finishAsync(this)
                }
            }.also { main.postDelayed(it, HARD_BLOCK_NS / 1_000_000L) }
        }

        fun recordEvent(event: MotionEvent, receiptNs: Long) {
            eventCount++
            eventAge.add(receiptNs - event.eventTimeNanos)
            if (pendingInputNanos == 0L) pendingInputNanos = receiptNs
            val history = event.historySize
            if (history > 0) {
                historyEvents++
                historySamples += history.toLong()
                for (i in 0 until history) recordSourceSample(event.getHistoricalEventTimeNanos(i))
            }
            recordSourceSample(event.eventTimeNanos)
            when (event.actionMasked) {
                MotionEvent.ACTION_DOWN -> { downCount++; inGesture = true }
                MotionEvent.ACTION_MOVE -> moveCount++
                MotionEvent.ACTION_UP -> { upCount++; inGesture = false }
                MotionEvent.ACTION_CANCEL -> { cancelCount++; inGesture = false }
            }
        }

        private fun recordSourceSample(timeNs: Long) {
            if (lastSourceSampleNanos != 0L && timeNs > lastSourceSampleNanos) sampleSpacing.add(timeNs - lastSourceSampleNanos)
            if (timeNs > lastSourceSampleNanos) lastSourceSampleNanos = timeNs
        }

        fun onFrame(frameNs: Long) {
            if (lastFrameNanos != 0L && frameNs > lastFrameNanos) {
                val delta = frameNs - lastFrameNanos
                uiFrames.add(delta)
                uiFrameCount++
                if (delta > nominalFrameNs * 3 / 2) uiJankCount++
            }
            lastFrameNanos = frameNs
            val input = pendingInputNanos
            if (input != 0L && frameNs >= input) {
                inputToUiFrame.add(frameNs - input)
                pendingInputNanos = 0L
            }
        }
    }

    data class BlockResult(
        val index: Int,
        val pair: Int,
        val transport: RendererArena.Transport,
        val durationMs: Double,
        val events: Long,
        val moves: Long,
        val historyEvents: Long,
        val historySamples: Long,
        val eventAgeP50Ms: Double,
        val eventAgeP95Ms: Double,
        val handlerP50Ms: Double,
        val handlerP95Ms: Double,
        val sourceSpacingP50Ms: Double,
        val sourceSpacingP95Ms: Double,
        val uiFrameP50Ms: Double,
        val uiFrameP95Ms: Double,
        val inputToUiFrameP50Ms: Double,
        val inputToUiFrameP95Ms: Double,
        val uiJankPct: Double,
        val appCpuMsPerSec: Double,
        val mainCpuMsPerSec: Double,
        val pssKb: Long,
        val heapUsedKb: Long,
        val gcCount: Long,
        val allocatedKb: Long,
        val energyNwh: Long,
        val currentUa: Int,
        val thermal: Int,
        val thermalHeadroom: Float,
        val refreshRate: Float,
        val rxBytes: Long,
        val txBytes: Long,
        val relaySubmitted: Long,
        val relayReleased: Long,
        val relayErrors: Long,
        val forcedFinish: Boolean
    )

    data class MetricDecision(
        val name: String,
        val unit: String,
        val medianDirectMinusRelay: Double,
        val ciLow: Double,
        val ciHigh: Double,
        val threshold: Double,
        val verdict: String
    )

    fun status(context: Context): Status {
        val state = run
        val p = pending
        val a = active
        val latest = context.getSharedPreferences("renderer-benchmark", Context.MODE_PRIVATE)
            .getString("latest-summary", "No completed measured run yet.").orEmpty()
        return when {
            state == null -> Status(false, 0, 0, "idle", latest)
            a != null -> Status(true, a.index + 1, state.order.size, "measuring ${methodLabel(a.transport)}", latest)
            p != null -> Status(true, p.index + 1, state.order.size, if (p.ready) "ready for next physical gesture" else "preparing renderer", latest)
            else -> Status(true, state.results.size + 1, state.order.size, "switching / analyzing", latest)
        }
    }

    fun start(context: Context, pairs: Int): Boolean {
        check(Looper.myLooper() == Looper.getMainLooper())
        if (run != null) return false
        val window = BubbleService.active?.window
        val session = Workspace.peek()?.selected?.session
        if (window == null || window.mode != FloatingMode.CHAT || session == null || !session.isOpen) {
            Toast.makeText(context, "Open a live floating chat/page before starting the renderer benchmark.", Toast.LENGTH_LONG).show()
            return false
        }
        val count = pairs.coerceIn(2, 12)
        val seed = SystemClock.elapsedRealtimeNanos() xor BuildFingerprint.seed()
        val order = ArrayList<RendererArena.Transport>(count * 2)
        val firstDirect = (seed and 1L) == 0L
        repeat(count) { pair ->
            val directFirst = if (pair % 2 == 0) firstDirect else !firstDirect
            if (directFirst) {
                order += RendererArena.Transport.DIRECT_GECKO_SURFACE
                order += RendererArena.Transport.RELAY_LATEST_BP
            } else {
                order += RendererArena.Transport.RELAY_LATEST_BP
                order += RendererArena.Transport.DIRECT_GECKO_SURFACE
            }
        }
        val app = context.applicationContext
        run = RunState(app, count, seed, order)
        PageTouchDispatch.arm = PageTouchDispatch.Arm.UNBUFFERED_140
        ensureFrameLoop()
        scheduleBlock(0)
        return true
    }

    fun cancel(message: String = "Renderer benchmark canceled.") {
        val state = run ?: return
        active?.targetFinish?.let(main::removeCallbacks)
        active?.hardFinish?.let(main::removeCallbacks)
        active = null
        pending = null
        run = null
        PageTouchDispatch.arm = PageTouchDispatch.Arm.UNBUFFERED_140
        RendererArena.transport = RendererArena.Transport.DIRECT_GECKO_SURFACE
        BubbleService.active?.window?.setRendererTransportForArena(RendererArena.Transport.DIRECT_GECKO_SURFACE)
        Toast.makeText(state.app, message, Toast.LENGTH_LONG).show()
    }

    /** Returns a non-zero token only for events inside a measured real floating-page block. */
    fun beforePage(view: View, event: MotionEvent): Long {
        var recorder = active
        if (recorder == null) {
            val p = pending ?: return 0L
            if (!p.ready || event.actionMasked != MotionEvent.ACTION_DOWN || !matchesActiveInput(view, p.transport)) return 0L
            recorder = p.recorder
            pending = null
            active = recorder
            recorder.begin(run?.app ?: return 0L)
        }
        if (!matchesActiveInput(view, recorder.transport)) return 0L
        val now = SystemClock.uptimeNanos()
        recorder.recordEvent(event, now)
        return now
    }

    fun afterPage(tokenNs: Long, event: MotionEvent) {
        if (tokenNs == 0L) return
        val recorder = active ?: return
        recorder.handler.add(SystemClock.uptimeNanos() - tokenNs)
        if ((event.actionMasked == MotionEvent.ACTION_UP || event.actionMasked == MotionEvent.ACTION_CANCEL) &&
            (recorder.finishRequested || SystemClock.uptimeNanos() - recorder.startedNanos >= TARGET_BLOCK_NS)) {
            finishAsync(recorder)
        }
    }

    private fun requestFinish(recorder: Recorder) {
        if (active !== recorder) return
        if (recorder.inGesture) recorder.finishRequested = true else finishAsync(recorder)
    }

    private fun finishAsync(recorder: Recorder) {
        if (active !== recorder) return
        main.post { finishBlock(recorder) }
    }

    private fun finishBlock(recorder: Recorder) {
        if (active !== recorder) return
        recorder.endedNanos = SystemClock.uptimeNanos()
        recorder.targetFinish?.let(main::removeCallbacks)
        recorder.hardFinish?.let(main::removeCallbacks)
        active = null
        val state = run ?: return
        val end = endSnapshot(state.app)
        val result = resultFrom(recorder, end)
        state.results += result
        val next = recorder.index + 1
        if (next >= state.order.size) complete(state)
        else {
            Toast.makeText(state.app, "Block ${recorder.index + 1}/${state.order.size} captured. Preparing the next hidden method…", Toast.LENGTH_SHORT).show()
            main.postDelayed({ if (run === state) scheduleBlock(next) }, BETWEEN_BLOCK_MS)
        }
    }

    private fun scheduleBlock(index: Int) {
        val state = run ?: return
        val transport = state.order[index]
        PageTouchDispatch.arm = PageTouchDispatch.Arm.UNBUFFERED_140
        RendererArena.transport = transport
        val window = BubbleService.active?.window
        if (window == null || window.mode != FloatingMode.CHAT) {
            cancel("Floating page disappeared; benchmark canceled.")
            return
        }
        pending = null
        window.setRendererTransportForArena(transport)
        val deadline = SystemClock.uptimeMillis() + READY_TIMEOUT_MS
        fun poll() {
            if (run !== state) return
            if (rendererReady(transport)) {
                val pendingBlock = PendingBlock(index, index / 2, transport, Recorder(index, index / 2, transport))
                pending = pendingBlock
                Toast.makeText(state.app, "Block ${index + 1}/${state.order.size}: method ready after the vibration. Repeat the same up/down scrolling workload.", Toast.LENGTH_SHORT).show()
                main.postDelayed({
                    if (run === state && pending === pendingBlock && rendererReady(transport)) {
                        pendingBlock.ready = true
                        BubbleService.active?.window?.transitionView?.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK)
                    } else if (run === state && pending === pendingBlock) poll()
                }, READY_SETTLE_MS)
            } else if (SystemClock.uptimeMillis() < deadline) main.postDelayed({ poll() }, 100L)
            else cancel("Renderer did not become stable/focused; benchmark canceled rather than recording a bad block.")
        }
        poll()
    }

    private fun rendererReady(transport: RendererArena.Transport): Boolean {
        val window = BubbleService.active?.window ?: return false
        val tab = Workspace.peek()?.selected ?: return false
        val session = tab.session ?: return false
        val host = window.pageHost ?: return false
        val input = session.textInput.view ?: return false
        if (window.mode != FloatingMode.CHAT || Workspace.peek()?.floatingVisible != true ||
            host.transport != transport || host.view.session !== session || !input.isAttachedToWindow ||
            !window.transitionView.hasWindowFocus() || !input.hasWindowFocus() || !input.isShown) return false
        val relay = relayStats()
        return when (transport) {
            RendererArena.Transport.DIRECT_GECKO_SURFACE -> input === host.view && input is LiveGeckoView && relay[0] == 0L && relay[1] == 0L && relay[4] == 0L && relay[5] == 0L
            RendererArena.Transport.RELAY_LATEST_BP -> input !== host.view && input is SurfaceView && relay[0] > 0L && relay[5] > 0L
        }
    }

    private fun matchesActiveInput(view: View, transport: RendererArena.Transport): Boolean {
        val window = BubbleService.active?.window ?: return false
        val session = Workspace.peek()?.selected?.session ?: return false
        val host = window.pageHost ?: return false
        if (host.transport != transport || session.textInput.view !== view || !view.isAttachedToWindow) return false
        return when (transport) {
            RendererArena.Transport.DIRECT_GECKO_SURFACE -> view === host.view && view is LiveGeckoView
            RendererArena.Transport.RELAY_LATEST_BP -> view !== host.view && view is SurfaceView
        }
    }

    private fun resultFrom(recorder: Recorder, end: EndSnapshot): BlockResult {
        val durationMs = (recorder.endedNanos - recorder.startedNanos).coerceAtLeast(1L) / 1_000_000.0
        val seconds = durationMs / 1000.0
        val start = recorder.start
        val processCpu = (end.processCpuMs - start.processCpuMs).coerceAtLeast(0L) / seconds
        val mainCpu = (end.mainCpuNs - start.mainCpuNs).coerceAtLeast(0L) / 1_000_000.0 / seconds
        val relaySubmitted = delta(end.relay, start.relay, 2)
        val relayReleased = delta(end.relay, start.relay, 3)
        val relayErrors = delta(end.relay, start.relay, 6)
        val energy = if (start.energyNwh >= 0 && end.energyNwh >= 0) end.energyNwh - start.energyNwh else Long.MIN_VALUE
        return BlockResult(
            recorder.index, recorder.pair, recorder.transport, durationMs,
            recorder.eventCount, recorder.moveCount, recorder.historyEvents, recorder.historySamples,
            recorder.eventAge.percentile(.50), recorder.eventAge.percentile(.95),
            recorder.handler.percentile(.50), recorder.handler.percentile(.95),
            recorder.sampleSpacing.percentile(.50), recorder.sampleSpacing.percentile(.95),
            recorder.uiFrames.percentile(.50), recorder.uiFrames.percentile(.95),
            recorder.inputToUiFrame.percentile(.50), recorder.inputToUiFrame.percentile(.95),
            if (recorder.uiFrameCount == 0L) Double.NaN else recorder.uiJankCount * 100.0 / recorder.uiFrameCount,
            processCpu, mainCpu, end.pssKb, end.heapUsedBytes / 1024L, end.gcCount, end.allocatedBytes / 1024L,
            energy, end.currentUa, end.thermal, end.headroom, end.refreshRate,
            end.rxBytes - start.rxBytes, end.txBytes - start.txBytes,
            relaySubmitted, relayReleased, relayErrors, recorder.forcedFinish
        )
    }

    private fun complete(state: RunState) {
        if (run !== state) return
        val decisions = decisions(state)
        val overall = overall(decisions)
        val text = humanReport(state, decisions, overall)
        val json = jsonReport(state, decisions, overall)
        val saved = saveReports(state.app, text, json)
        val summary = "$overall\n${decisions.joinToString("\n") { "${it.name}: ${it.verdict}" }}\n${if (saved.isBlank()) "Saved in app benchmark files." else "Saved: $saved"}"
        state.app.getSharedPreferences("renderer-benchmark", Context.MODE_PRIVATE).edit()
            .putString("latest-summary", summary).apply()
        run = null
        pending = null
        active = null
        PageTouchDispatch.arm = PageTouchDispatch.Arm.UNBUFFERED_140
        RendererArena.transport = RendererArena.Transport.DIRECT_GECKO_SURFACE
        BubbleService.active?.window?.setRendererTransportForArena(RendererArena.Transport.DIRECT_GECKO_SURFACE)
        Toast.makeText(state.app, "Renderer benchmark complete. Opening the report summary.", Toast.LENGTH_LONG).show()
        main.postDelayed({
            state.app.startActivity(Intent(state.app, RendererArenaActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP))
        }, 700L)
    }

    private fun decisions(state: RunState): List<MetricDecision> {
        val pairs = (0 until state.pairs).mapNotNull { pair ->
            val blocks = state.results.filter { it.pair == pair }
            val direct = blocks.firstOrNull { it.transport == RendererArena.Transport.DIRECT_GECKO_SURFACE }
            val relay = blocks.firstOrNull { it.transport == RendererArena.Transport.RELAY_LATEST_BP }
            if (direct != null && relay != null) direct to relay else null
        }
        fun metric(name: String, unit: String, threshold: (List<Double>) -> Double, value: (BlockResult) -> Double): MetricDecision {
            val diffs = pairs.mapNotNull { (d, r) ->
                val dv = value(d); val rv = value(r)
                if (dv.isFinite() && rv.isFinite()) dv - rv else null
            }
            if (diffs.isEmpty()) return MetricDecision(name, unit, Double.NaN, Double.NaN, Double.NaN, Double.NaN, "UNAVAILABLE")
            val center = median(diffs)
            val ci = bootstrapMedianCi(diffs, state.seed xor name.hashCode().toLong())
            val t = threshold(diffs)
            val verdict = when {
                ci.second < -t -> "DIRECT WIN"
                ci.first > t -> "RELAY WIN"
                ci.first >= -t && ci.second <= t -> "EQUIVALENT"
                else -> "INCONCLUSIVE"
            }
            return MetricDecision(name, unit, center, ci.first, ci.second, t, verdict)
        }
        val pooledCpu = pairs.flatMap { listOf(it.first.appCpuMsPerSec, it.second.appCpuMsPerSec) }.filter { it.isFinite() }
        val cpuThreshold = max(1.0, (pooledCpu.average().takeIf { it.isFinite() } ?: 0.0) * .03)
        return listOf(
            metric("Input event age p95", "ms", { .25 }) { it.eventAgeP95Ms },
            metric("Page handler time p95", "ms", { .10 }) { it.handlerP95Ms },
            metric("Bubble process CPU", "ms CPU / s", { cpuThreshold }) { it.appCpuMsPerSec },
            metric("Bubble main-thread CPU", "ms CPU / s", { max(.5, cpuThreshold / 2) }) { it.mainCpuMsPerSec },
            metric("App Choreographer frame p95", "ms", { .25 }) { it.uiFrameP95Ms },
            metric("Input to next app frame p95", "ms", { .25 }) { it.inputToUiFrameP95Ms },
            metric("App Choreographer jank", "%", { .50 }) { it.uiJankPct }
        )
    }

    private fun overall(decisions: List<MetricDecision>): String {
        val primary = decisions.take(4).filter { it.verdict != "UNAVAILABLE" }
        val direct = primary.count { it.verdict == "DIRECT WIN" }
        val relay = primary.count { it.verdict == "RELAY WIN" }
        val equivalent = primary.count { it.verdict == "EQUIVALENT" }
        return when {
            direct >= 2 && relay == 0 -> "Overall: DIRECT favored by measured app/input-overhead metrics"
            relay >= 2 && direct == 0 -> "Overall: RELAY favored by measured app/input-overhead metrics"
            primary.isNotEmpty() && equivalent == primary.size -> "Overall: equivalent within predefined practical bounds"
            else -> "Overall: mixed / inconclusive — no honest single winner from these software metrics"
        }
    }

    private fun humanReport(state: RunState, decisions: List<MetricDecision>, overall: String): String = buildString {
        appendLine("Bubble renderer benchmark")
        appendLine("Generated: ${java.util.Date()}")
        appendLine("Pairs: ${state.pairs}; blocks: ${state.results.size}; seed: ${state.seed}")
        appendLine("Input policy: UNBUFFERED_140 for BOTH renderer arms")
        appendLine("Renderer A/B: DIRECT GeckoView SurfaceView vs relay_latest_bp")
        appendLine()
        appendLine(overall)
        appendLine()
        appendLine("PAIRED DECISIONS (direct minus relay; lower is better)")
        decisions.forEach { d ->
            appendLine("${d.name}: ${fmt(d.medianDirectMinusRelay)} ${d.unit}; 95% bootstrap CI [${fmt(d.ciLow)}, ${fmt(d.ciHigh)}], practical bound ±${fmt(d.threshold)} => ${d.verdict}")
        }
        appendLine()
        appendLine("RAW BLOCKS")
        state.results.forEach { b ->
            appendLine("block=${b.index + 1} pair=${b.pair + 1} method=${methodLabel(b.transport)} duration=${fmt(b.durationMs)}ms events=${b.events} moves=${b.moves} history=${b.historyEvents}/${b.historySamples} eventAgeP95=${fmt(b.eventAgeP95Ms)}ms handlerP95=${fmt(b.handlerP95Ms)}ms sourceSpacingP95=${fmt(b.sourceSpacingP95Ms)}ms appFrameP95=${fmt(b.uiFrameP95Ms)}ms inputToAppFrameP95=${fmt(b.inputToUiFrameP95Ms)}ms appJank=${fmt(b.uiJankPct)}% cpu=${fmt(b.appCpuMsPerSec)}ms/s mainCpu=${fmt(b.mainCpuMsPerSec)}ms/s pss=${b.pssKb}KB heap=${b.heapUsedKb}KB energy=${if (b.energyNwh == Long.MIN_VALUE) "unsupported" else "${b.energyNwh}nWh"} current=${b.currentUa}uA thermal=${b.thermal} headroom=${fmt(b.thermalHeadroom.toDouble())} refresh=${fmt(b.refreshRate.toDouble())}Hz net=${b.rxBytes}/${b.txBytes} relaySubmit=${b.relaySubmitted} relayRelease=${b.relayReleased} relayErrors=${b.relayErrors}")
        }
        appendLine()
        appendLine("SCOPE / HONESTY")
        appendLine("- Event age measures MotionEvent timestamp -> Bubble handler receipt. Handler time ends after the existing Gecko/APZ Java entry returns.")
        appendLine("- App Choreographer metrics describe Bubble's UI scheduler, not Gecko/WebRender or SurfaceFlinger presentation FPS.")
        appendLine("- Input->next app frame is NOT touch-to-photon latency.")
        appendLine("- CPU/PSS/heap/GC are Bubble app-process measurements; Gecko/system compositor work may run in other processes.")
        appendLine("- Battery/thermal/network readings are device-wide/noisy and are context, not automatic winner metrics.")
        appendLine("- Actual contact-to-photon requires an external high-speed camera/photodiode. Perfetto/FrameTimeline is the preferred software follow-up for compositor/scheduler analysis.")
        appendLine("- Relay submission counters are route proof: direct should add no relay submissions; relay should add them during rendered work.")
    }

    private fun jsonReport(state: RunState, decisions: List<MetricDecision>, overall: String): String {
        val root = JSONObject()
        root.put("generatedWallMs", System.currentTimeMillis())
        root.put("pairs", state.pairs)
        root.put("seed", state.seed)
        root.put("inputPolicy", "UNBUFFERED_140")
        root.put("overall", overall)
        val metrics = JSONArray()
        decisions.forEach { d ->
            metrics.put(JSONObject().put("name", d.name).put("unit", d.unit).put("directMinusRelay", finiteOrNull(d.medianDirectMinusRelay))
                .put("ciLow", finiteOrNull(d.ciLow)).put("ciHigh", finiteOrNull(d.ciHigh)).put("threshold", finiteOrNull(d.threshold)).put("verdict", d.verdict))
        }
        root.put("decisions", metrics)
        val blocks = JSONArray()
        state.results.forEach { b ->
            blocks.put(JSONObject()
                .put("index", b.index).put("pair", b.pair).put("renderer", b.transport.name).put("durationMs", b.durationMs)
                .put("events", b.events).put("moves", b.moves).put("historyEvents", b.historyEvents).put("historySamples", b.historySamples)
                .put("eventAgeP50Ms", finiteOrNull(b.eventAgeP50Ms)).put("eventAgeP95Ms", finiteOrNull(b.eventAgeP95Ms))
                .put("handlerP50Ms", finiteOrNull(b.handlerP50Ms)).put("handlerP95Ms", finiteOrNull(b.handlerP95Ms))
                .put("sourceSpacingP50Ms", finiteOrNull(b.sourceSpacingP50Ms)).put("sourceSpacingP95Ms", finiteOrNull(b.sourceSpacingP95Ms))
                .put("uiFrameP50Ms", finiteOrNull(b.uiFrameP50Ms)).put("uiFrameP95Ms", finiteOrNull(b.uiFrameP95Ms))
                .put("inputToUiFrameP50Ms", finiteOrNull(b.inputToUiFrameP50Ms)).put("inputToUiFrameP95Ms", finiteOrNull(b.inputToUiFrameP95Ms))
                .put("uiJankPct", finiteOrNull(b.uiJankPct)).put("appCpuMsPerSec", b.appCpuMsPerSec).put("mainCpuMsPerSec", b.mainCpuMsPerSec)
                .put("pssKb", b.pssKb).put("heapUsedKb", b.heapUsedKb).put("gcCount", b.gcCount).put("allocatedKb", b.allocatedKb)
                .put("energyNwh", if (b.energyNwh == Long.MIN_VALUE) JSONObject.NULL else b.energyNwh).put("currentUa", b.currentUa)
                .put("thermal", b.thermal).put("thermalHeadroom", finiteOrNull(b.thermalHeadroom.toDouble())).put("refreshRate", b.refreshRate)
                .put("rxBytes", b.rxBytes).put("txBytes", b.txBytes).put("relaySubmitted", b.relaySubmitted).put("relayReleased", b.relayReleased)
                .put("relayErrors", b.relayErrors).put("forcedFinish", b.forcedFinish))
        }
        root.put("blocks", blocks)
        root.put("scope", "Software A/B in the same process/profile/GeckoSession and real floating window. Not touch-to-photon or direct SurfaceFlinger present timestamps.")
        return root.toString(2)
    }

    private fun saveReports(context: Context, text: String, json: String): String {
        val stamp = java.text.SimpleDateFormat("yyyyMMdd-HHmmss", java.util.Locale.US).format(java.util.Date())
        val dir = File(context.getExternalFilesDir(null), "renderer-benchmarks").apply { mkdirs() }
        File(dir, "renderer-$stamp.txt").writeText(text)
        File(dir, "renderer-$stamp.json").writeText(json)
        return runCatching {
            val values = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, "Bubble-renderer-benchmark-$stamp.txt")
                put(MediaStore.MediaColumns.MIME_TYPE, "text/plain")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/Bubble Benchmarks")
                put(MediaStore.MediaColumns.IS_PENDING, 1)
            }
            val resolver = context.contentResolver
            val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values) ?: return@runCatching ""
            resolver.openOutputStream(uri)?.bufferedWriter()?.use { it.write(text) }
            values.clear(); values.put(MediaStore.MediaColumns.IS_PENDING, 0); resolver.update(uri, values, null, null)
            "Downloads/Bubble Benchmarks/Bubble-renderer-benchmark-$stamp.txt"
        }.getOrDefault("")
    }

    private fun endSnapshot(context: Context): EndSnapshot {
        val runtime = Runtime.getRuntime()
        val pm = context.getSystemService(PowerManager::class.java)
        return EndSnapshot(
            Process.getElapsedCpuTime(), Debug.threadCpuTimeNanos(), energyCounter(context), currentNow(context),
            safeUidRx(), safeUidTx(), Debug.getPss(), runtime.totalMemory() - runtime.freeMemory(),
            runtimeStatLong("art.gc.gc-count"), runtimeStatLong("art.gc.bytes-allocated"),
            pm.currentThermalStatus, runCatching { pm.getThermalHeadroom(10) }.getOrDefault(Float.NaN),
            currentRefreshRate() ?: Float.NaN, relayStats()
        )
    }

    private fun currentRefreshRate(): Float? = BubbleService.active?.window?.transitionView?.display?.refreshRate
    private fun relayStats(): LongArray = runCatching { NativeAhbBridge.nativeDebugStats() }.getOrElse { LongArray(10) }
    private fun delta(end: LongArray, start: LongArray, index: Int): Long = (end.getOrElse(index) { 0L } - start.getOrElse(index) { 0L }).coerceAtLeast(0L)
    private fun safeUidRx(): Long = TrafficStats.getUidRxBytes(Process.myUid()).coerceAtLeast(0L)
    private fun safeUidTx(): Long = TrafficStats.getUidTxBytes(Process.myUid()).coerceAtLeast(0L)
    private fun runtimeStatLong(key: String): Long = runCatching { Debug.getRuntimeStat(key)?.toLongOrNull() ?: -1L }.getOrDefault(-1L)
    private fun energyCounter(context: Context): Long = runCatching {
        context.getSystemService(BatteryManager::class.java).getLongProperty(BatteryManager.BATTERY_PROPERTY_ENERGY_COUNTER)
    }.getOrDefault(-1L).let { if (it <= 0L) -1L else it }
    private fun currentNow(context: Context): Int = runCatching {
        context.getSystemService(BatteryManager::class.java).getIntProperty(BatteryManager.BATTERY_PROPERTY_CURRENT_NOW)
    }.getOrDefault(Int.MIN_VALUE)

    private fun ensureFrameLoop() {
        if (frameLoopPosted || run == null) return
        frameLoopPosted = true
        Choreographer.getInstance().postFrameCallback(frameCallback)
    }

    private fun methodLabel(transport: RendererArena.Transport): String = when (transport) {
        RendererArena.Transport.DIRECT_GECKO_SURFACE -> "DIRECT"
        RendererArena.Transport.RELAY_LATEST_BP -> "RELAY"
    }

    private fun median(values: List<Double>): Double {
        if (values.isEmpty()) return Double.NaN
        val sorted = values.sorted()
        val mid = sorted.size / 2
        return if (sorted.size % 2 == 1) sorted[mid] else (sorted[mid - 1] + sorted[mid]) / 2.0
    }

    private fun bootstrapMedianCi(values: List<Double>, seed: Long): Pair<Double, Double> {
        if (values.size == 1) return values[0] to values[0]
        val random = Random(seed)
        val samples = DoubleArray(2000)
        val temp = DoubleArray(values.size)
        repeat(samples.size) { iteration ->
            for (i in temp.indices) temp[i] = values[random.nextInt(values.size)]
            temp.sort()
            val mid = temp.size / 2
            samples[iteration] = if (temp.size % 2 == 1) temp[mid] else (temp[mid - 1] + temp[mid]) / 2.0
        }
        samples.sort()
        return samples[(samples.size * .025).toInt().coerceIn(samples.indices)] to
            samples[(samples.size * .975).toInt().coerceIn(samples.indices)]
    }

    private fun fmt(value: Double): String = if (!value.isFinite()) "n/a" else String.format(java.util.Locale.US, "%.3f", value)
    private fun finiteOrNull(value: Double): Any = if (value.isFinite()) value else JSONObject.NULL

    private object BuildFingerprint {
        fun seed(): Long {
            var value = 0xcbf29ce484222325UL.toLong()
            for (c in android.os.Build.FINGERPRINT) value = (value xor c.code.toLong()) * 0x100000001b3L
            return value
        }
    }
}
