#!/usr/bin/env python3
"""Materialise reviewed v2 workload/report source; used once by the staging workflow."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def put(path,text):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
put('renderer-probe/src/main/assets/workload.html',r'''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';connect-src 'none'"><style>
*{box-sizing:border-box}html,body{margin:0;background:#05070b;color:#e8eef5;font:16px system-ui;overflow:hidden}#viewport{height:100vh;overflow:auto}#messages{padding:24px 14px 80px}article{padding:16px;margin:12px 0;background:#18212d;border:1px solid #364454;border-radius:16px}article:nth-child(even){margin-left:28px}p{line-height:1.5}pre{padding:12px;background:#080c13;white-space:pre-wrap;font-size:13px}canvas{position:fixed;inset:0;width:100%;height:100%;display:none}#marker{position:fixed;top:0;left:0;padding:5px 10px;background:#183b36;font:12px monospace;z-index:6}.effect{position:fixed;width:120px;height:120px;backdrop-filter:blur(12px);background:#9aafce22;border:1px solid #bbcddd44;border-radius:22px;will-change:transform;display:none}
</style></head><body><div id="viewport"><div id="messages"></div></div><canvas id="paint"></canvas><canvas id="gpu"></canvas><div id="marker"></div><script>
'use strict';const C=__CONFIG__,level=Math.max(1,Math.min(6,C.intensity||1)),pane=document.getElementById('viewport'),rows=document.getElementById('messages'),marker=document.getElementById('marker');
const errors=[],raf=[],cpu=[],inputDelay=[],scrollSamples=[],gpuTimes=[];let done=false,started=null,measureStart=0,last=0,frameId=0,workUnits=0,truncated=false,observer=null;
function send(phase,extra={}){document.title='BPROBE:'+JSON.stringify({token:C.token,phase,...extra});}
function fail(reason){if(done)return;done=true;errors.push(reason);send('workload-failed',{reason,errors});}
addEventListener('error',e=>fail(String(e.message)));addEventListener('unhandledrejection',e=>fail(String(e.reason)));
for(let i=0;i<180*level;i++){const a=document.createElement('article');a.innerHTML='<h3>Local renderer workload '+i+'</h3><p>Identical full-resolution content, fixed node count, no accounts or networking.</p><pre>frame = render(scene);\npresent(frame, acquireFence);</pre><p>Measure production separately from presentation.</p>';rows.appendChild(a);}
const initialNodes=rows.childElementCount,longTasks=[],visibility=[];let longTaskApiSupported=false;
const entries=typeof PerformanceObserver==='function'?(PerformanceObserver.supportedEntryTypes||[]):[];
if(entries.includes('longtask'))try{observer=new PerformanceObserver(list=>{for(const e of list.getEntries())if(measureStart&&e.startTime>=measureStart)longTasks.push(e.duration);});observer.observe({type:'longtask'});longTaskApiSupported=true;}catch(_){observer=null;}
document.addEventListener('visibilitychange',()=>visibility.push({at:performance.now(),state:document.visibilityState}));
for(const kind of ['pointerdown','pointermove','touchstart','touchmove','wheel'])document.addEventListener(kind,e=>{if(measureStart&&inputDelay.length<16000){const delay=performance.now()-e.timeStamp;if(delay>=0&&delay<10000)inputDelay.push(delay);}}, {passive:true});
const canvas=document.getElementById('paint'),gpuCanvas=document.getElementById('gpu');let ctx=null,gl=null,ext=null,program=null,timeLocation=null,queries=[],currentQuery=null,querySkipped=0,gpuDisjoint=0,gpuTimerSupported=false;const effects=[];
function size(c){c.width=Math.round(innerWidth*devicePixelRatio);c.height=Math.round(innerHeight*devicePixelRatio);}
if(C.workload==='repaint'){size(canvas);ctx=canvas.getContext('2d',{alpha:false});if(!ctx)fail('CANVAS_2D_UNAVAILABLE');canvas.style.display='block';}
if(C.workload==='css')for(let i=0;i<24*level;i++){const v=document.createElement('div');v.className='effect';v.style.left=(i*73%Math.max(1,innerWidth-120))+'px';v.style.top=(i*137%Math.max(1,innerHeight-120))+'px';document.body.appendChild(v);effects.push(v);}
function shader(type,source){const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;}
if(C.workload==='webgl')try{size(gpuCanvas);gl=gpuCanvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:false});if(!gl)throw Error('WEBGL2_UNAVAILABLE');gpuCanvas.style.display='block';program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'#version 300 es\nvoid main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));gl_Position=vec4(p*2.0-1.0,0,1);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;uniform float uTime;out vec4 color;void main(){vec2 p=gl_FragCoord.xy*.003;float v=uTime*.1;for(int i=0;i<'+(12*level)+';i++){v=sin(v+p.x*1.17)+cos(p.y+v*.73);p+=vec2(v*.017);}color=vec4(.5+.5*sin(v),.5+.5*cos(v+1.0),.5+.5*sin(v+2.0),1);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);timeLocation=gl.getUniformLocation(program,'uTime');gl.viewport(0,0,gpuCanvas.width,gpuCanvas.height);ext=gl.getExtension('EXT_disjoint_timer_query_webgl2');gpuTimerSupported=!!ext;gpuCanvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('WEBGL_CONTEXT_LOST');});}catch(e){fail(String(e.message));}
let streamTicks=0;const stream=document.createElement('article'),streamText=document.createTextNode(''),streamCode=document.createElement('pre');stream.appendChild(streamText);stream.appendChild(streamCode);if(C.workload==='stream')rows.appendChild(stream);
const readinessStart=performance.now();let initialContentfulPaintMs=null;marker.textContent=C.label+' / '+C.workload+' / waiting for paint';
function stat(a){if(!a.length)return {intervals:[],hz:null,p50:null,p95:null,p99:null};const s=[...a].sort((a,b)=>a-b),q=p=>s[Math.ceil(p*s.length)-1];return {intervals:a,hz:1000*a.length/a.reduce((a,b)=>a+b,0),p50:q(.5),p95:q(.95),p99:q(.99)};}
function measureGpu(t){if(ext){if(gl.getParameter(ext.GPU_DISJOINT_EXT)){gpuDisjoint++;for(const q of queries)gl.deleteQuery(q.query);queries=[];}else while(queries.length&&gl.getQueryParameter(queries[0].query,gl.QUERY_RESULT_AVAILABLE)){const q=queries.shift(),ns=gl.getQueryParameter(q.query,gl.QUERY_RESULT);if(q.measured)gpuTimes.push(ns/1e6);gl.deleteQuery(q.query);}if(queries.length<8){currentQuery=gl.createQuery();gl.beginQuery(ext.TIME_ELAPSED_EXT,currentQuery);}else querySkipped++;}gl.uniform1f(timeLocation,t/1000);gl.drawArrays(gl.TRIANGLES,0,3);if(currentQuery){gl.endQuery(ext.TIME_ELAPSED_EXT);queries.push({query:currentQuery,measured:!!measureStart});currentQuery=null;}}
function frame(t){if(done)return;const begin=performance.now();if(started===null){const fcp=performance.getEntriesByType('paint').find(e=>e.name==='first-contentful-paint');if(!fcp){if(t-readinessStart>=15000){done=true;send('readiness-failed',{reason:'PAGE_FIRST_PAINT_TIMEOUT'});}else requestAnimationFrame(frame);return;}initialContentfulPaintMs=fcp.startTime;started=t;send('warmup',{initialContentfulPaintMs,cssWidth:innerWidth,cssHeight:innerHeight,dpr:devicePixelRatio,userAgent:navigator.userAgent});if(C.workload==='apz')pane.scrollTop=(pane.scrollHeight-pane.clientHeight)*.5;for(const v of effects)v.style.display='block';marker.textContent=C.label+' / '+C.workload;}
const elapsed=t-started;if(!measureStart&&elapsed>=C.warmupMs){measureStart=t;last=t;send('measure',{pageStartMs:t});}else if(measureStart){if(raf.length<16000)raf.push(t-last);else truncated=true;last=t;}
const max=pane.scrollHeight-pane.clientHeight;
if(C.workload==='scroll')pane.scrollTop=(.5-.5*Math.cos(elapsed*Math.PI/4000))*max;
if(C.workload==='stream'){const target=Math.floor(elapsed/50);while(streamTicks<target){streamTicks++;streamText.appendData(' token'+streamTicks+' '.repeat(level));if(streamTicks%16===0)streamCode.textContent+='step('+streamTicks+');\n';workUnits++;}pane.scrollTop=pane.scrollHeight;}
if(C.workload==='repaint'){const w=canvas.width,h=canvas.height;ctx.fillStyle='#070c15';ctx.fillRect(0,0,w,h);for(let i=0;i<256*level;i++){ctx.fillStyle='hsl('+((i*19+elapsed*.05)%360)+' 65% 55%)';ctx.fillRect((i*157+elapsed*.18)%w,(i*113+elapsed*.08)%h,32+i%87,40+i%61);}workUnits+=256*level;}
if(C.workload==='css'){effects.forEach((v,i)=>v.style.transform='translate('+Math.sin(elapsed*.001+i)*45+'px,'+Math.cos(elapsed*.0012+i)*45+'px) rotate('+Math.sin(elapsed*.0006+i)*20+'deg)');workUnits+=effects.length;}
if(C.workload==='webgl'){measureGpu(elapsed);workUnits++;}
frameId++;if(measureStart){if(cpu.length<16000)cpu.push(performance.now()-begin);if(frameId%12===0)scrollSamples.push([t,pane.scrollTop]);}
if(measureStart&&t-measureStart>=C.measureMs){done=true;observer?.disconnect();send('done',{raf:stat(raf),durationMs:t-measureStart,frameId,cssWidth:innerWidth,cssHeight:innerHeight,dpr:devicePixelRatio,initialNodes,initialContentfulPaintMs,finalScroll:pane.scrollTop,callbackCpuMs:cpu,inputEventTimestampDelayMs:inputDelay,inputTimingScope:'event timeStamp to JavaScript handler; NOT touch-to-photon',scrollSamples,longTasks,longTaskApiSupported,gpuDrawMs:gpuTimes,gpuTimerSupported,gpuDisjoint,gpuQueriesPending:queries.filter(q=>q.measured).length,gpuQuerySkipped:querySkipped,gpuScope:'WebGL test draw only; NOT total Gecko/WebRender GPU',workUnitsIncludingWarmup:workUnits,streamTicksIncludingWarmup:streamTicks,visibility,visibilityState:document.visibilityState,errors,samplesTruncated:truncated});return;}
requestAnimationFrame(frame);}
if(!done){send('waiting-for-paint',{paintEntryTypes:entries});requestAnimationFrame(frame);}
</script></body></html>''')
put('renderer-probe/src/main/java/com/mekromn/bubble/probe/ReportActivity.java',r'''package com.mekromn.bubble.probe;
import android.app.Activity;import android.os.Bundle;import android.webkit.*;import android.widget.TextView;import java.io.*;import java.util.concurrent.*;
public final class ReportActivity extends Activity {
 private WebView web;private final ExecutorService worker=Executors.newSingleThreadExecutor();
 @Override public void onCreate(Bundle state){super.onCreate(state);TextView waiting=new TextView(this);waiting.setText("Building detailed report from recorded samples…");waiting.setPadding(24,80,24,24);setContentView(waiting);worker.execute(()->{try{File suite=ReportWriter.latest(this);if(suite==null)throw new IOException("No saved suite");File out=new File(getCacheDir(),"renderer-report.html");ReportWriter.write(this,suite,out);runOnUiThread(()->show(out));}catch(Exception e){runOnUiThread(()->waiting.setText("Report unavailable: "+e));}});}
 @android.annotation.SuppressLint("SetJavaScriptEnabled") private void show(File file){if(isFinishing()||isDestroyed())return;web=new WebView(this);web.setBackgroundColor(0xff080c12);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{if(r.getUrl().toString().equals("https://bubble-probe.invalid/report"))return new WebResourceResponse("text/html","UTF-8",new FileInputStream(file));}catch(IOException ignored){}return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}});setContentView(web);web.loadUrl("https://bubble-probe.invalid/report");}
 @Override public void onDestroy(){worker.shutdownNow();if(web!=null)web.destroy();super.onDestroy();}
}''')
put('renderer-probe/src/main/assets/report-head.html',r'''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';connect-src 'none'"><title>Renderer Lab</title><style>:root{font-family:system-ui;color-scheme:dark;background:#080c12;color:#e8eff8}body{margin:auto;max-width:1500px;padding:22px}.cards{display:flex;gap:12px;flex-wrap:wrap}.card{padding:16px;border:1px solid #354456;border-radius:12px;flex:1;background:#142030}.card b{display:block;font-size:28px}.warn{padding:15px;background:#2d2517;border:1px solid #6d5b38;border-radius:12px;line-height:1.6}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:12px;text-align:left;white-space:nowrap;border-bottom:1px solid #304054}tr[data-i]{cursor:pointer}tr:hover{background:#1b3043}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}canvas{width:100%;height:220px;background:#121c28}.plots{display:flex;gap:18px;flex-wrap:wrap}.plots>div{flex:1;min-width:270px}details{border:1px solid #3a485b;border-radius:12px;padding:14px;margin:12px 0}.muted{color:#a5b5cb;line-height:1.6}select{padding:10px;background:#142437;color:inherit}#detail{display:none}</style></head><body><p class="muted">BUBBLE / RENDERER LAB · LOCAL EVIDENCE</p><h1>Latency, pacing and validity</h1><div id="overview" class="cards"></div><p class="warn" id="notice"></p><label>Trials <select id="filter"><option value="all">All, including failures</option><option value="valid">Eligible only</option><option value="invalid">Invalid / unconfirmed</option></select></label><div class="scroll"><table><thead><tr><th>Renderer / host</th><th>Workload / block</th><th>Validity</th><th>rAF Hz</th><th>p95 / p99</th><th>Worst gap</th><th>Gaps >1.5T</th><th>Acq→present p50 / p95</th><th>Fence coverage</th><th>Runner CPU %</th></tr></thead><tbody id="trials"></tbody></table></div><p class="muted">Tap a row for distributions. Missing fence observations are not proven frame drops. Root-window GPU metrics are not Gecko GPU time.</p><section id="detail"><h2 id="title"></h2><p id="issues" class="warn"></p><div class="plots"><div><h3>Callback interval histogram</h3><canvas id="hist"></canvas></div><div><h3>Worst callback gap by second</h3><canvas id="series"></canvas></div></div><h3>Pipeline / resources / scope</h3><pre id="metrics"></pre></section><h2>Repeated matched comparisons</h2><p class="muted">Confidence intervals use independent complete paired blocks, never individual frames. Six valid blocks minimum. Negative means lower for the named metric, not an overall renderer victory.</p><div id="comparisons"></div><script>__ANALYSIS_JS__</script><script>const ProbeReports=[];</script>''')
put('renderer-probe/src/main/assets/report-tail.html',r'''<script>'use strict';const R=ProbeAnalysis.compareAnalyzed(ProbeReports),$=id=>document.getElementById(id),f=x=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(2):'—';function el(tag,s){const x=document.createElement(tag);x.textContent=s;return x;}for(const [k,v] of [['Trials',R.trials.length],['Eligible',R.trials.filter(t=>t.eligible).length],['Excluded',R.trials.filter(t=>!t.eligible).length],['Supported intervals',R.comparisons.filter(c=>c.statistics.ci).length]]){const c=el('div','');c.className='card';c.append(el('b',v),el('span',k));$('overview').append(c);}$('notice').textContent=R.notice;
function render(){$('trials').textContent='';R.trials.forEach((t,i)=>{if($('filter').value==='valid'&&!t.eligible||$('filter').value==='invalid'&&t.eligible)return;const tr=document.createElement('tr');tr.dataset.i=i;for(const s of [t.variant+' / '+t.host,t.workload+' ×'+t.intensity+' / '+t.block,t.eligible?'eligible':t.status+' / '+t.issues.join(', '),f(t.raf.hz),f(t.raf.p95)+' / '+f(t.raf.p99),f(t.raf.max),f(t.raf.overOneAndHalfBudgetPct)+'%',f(t.pipe.acquireToPresent.p50)+' / '+f(t.pipe.acquireToPresent.p95),f(t.pipe.presentCoverage===null?null:t.pipe.presentCoverage*100)+'%',f(t.res.runnerCpuPct.mean)])tr.append(el('td',s));tr.onclick=()=>detail(t);$('trials').append(tr);});}
function plot(id,a,labels){const c=$(id),scale=devicePixelRatio||1,w=c.clientWidth;c.width=w*scale;c.height=220*scale;const x=c.getContext('2d');x.scale(scale,scale);if(!a.length){x.fillStyle='#d0dde8';x.fillText('Not measured',20,40);return;}const max=Math.max(...a,1),bw=(w-50)/a.length;a.forEach((v,i)=>{x.fillStyle='#7bd6c1';const h=150*v/max;x.fillRect(38+i*bw,170-h,Math.max(1,bw-2),h);if(labels){x.save();x.translate(40+i*bw,190);x.rotate(.5);x.fillStyle='#b4c5d7';x.font='10px system-ui';x.fillText(labels[i],0,0);x.restore();}});x.fillStyle='#b4c5d7';x.fillText(f(max),2,15);}
function detail(t){$('detail').style.display='block';$('title').textContent=t.variant+' / '+t.host+' / '+t.file;$('issues').textContent=[...t.issues,...t.warnings].join(' · ')||'No recorded exclusion. Unmeasured quantities remain unknown.';plot('hist',t.raf.histogram.map(h=>h.n),t.raf.histogram.map(h=>h.upperMs===null?'>250':'≤'+h.upperMs));plot('series',t.raf.seconds.map(s=>s.maxMs));$('metrics').textContent=JSON.stringify({pipeline:t.pipe,additionalChannels:t.channels,resources:t.res,rootOnlyJankPct:t.rootJankPct,callbackStalls50ms:t.raf.stalls50ms,longestLateBurst:t.raf.longestLateBurst},null,2);$('detail').scrollIntoView({behavior:'smooth'});}
for(const c of R.comparisons){const d=document.createElement('details');d.append(el('summary',c.label+' / '+c.workload+' / '+c.title+' / '+c.statistics.decision));d.append(el('pre',JSON.stringify({statistics:c.statistics,unit:c.unit,excluded:c.excluded},null,2)));$('comparisons').append(d);}if(!R.comparisons.length)$('comparisons').append(el('p','No complete eligible comparable pairs.'));$('filter').onchange=render;render();</script></body></html>''')
put('tools/test-renderer-probe.cjs',r'''const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const html=fs.readFileSync('renderer-probe/src/main/assets/workload.html','utf8'),native=fs.readFileSync('renderer-probe/src/main/cpp/probe.cpp','utf8');new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('__CONFIG__','{}'));assert(!native.includes('ANativeWindow_setSharedBufferMode'));assert(!native.includes('ANativeWindow_setAutoRefresh'));assert(!native.includes('AImageReader_acquireLatestImageAsync('));assert(native.includes('ASurfaceTransaction_setBufferWithRelease'));assert(native.includes('AImage_deleteAsync(lease->image,fence)'));assert(html.includes("entries.includes('longtask')"));assert(html.includes('PAGE_FIRST_PAINT_TIMEOUT'));for(const c of ['apz','stream','repaint','css','webgl','scroll'])assert(html.includes("C.workload==='"+c+"'"));console.log('v2 source guards and workload JavaScript parse passed; actual browser execution is a separate test.');''')
put('tools/probe-browser-test.cjs',r'''const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');(async()=>{const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{for(const workload of ['apz','stream','repaint','css','webgl','scroll']){const page=await browser.newPage({viewport:{width:400,height:700},deviceScaleFactor:2});const token='browser-test-'+workload;const html=fs.readFileSync('renderer-probe/src/main/assets/workload.html','utf8').replace('__CONFIG__',JSON.stringify({token,label:token,workload,intensity:1,warmupMs:200,measureMs:1000}));await page.route('**/*',route=>route.request().url()==='https://probe.test/'?route.fulfill({status:200,contentType:'text/html',body:html}):route.abort());await page.goto('https://probe.test/');await page.waitForFunction(()=>document.title.includes('"phase":"done"')||document.title.includes('"phase":"workload-failed"')||document.title.includes('"phase":"readiness-failed"'),null,{timeout:30000});const report=JSON.parse((await page.title()).slice('BPROBE:'.length));assert.equal(report.phase,'done',JSON.stringify(report));assert.equal(report.token,token);assert(report.durationMs>=1000);assert(report.raf.intervals.length>5);assert(report.initialContentfulPaintMs>=0);assert.equal(report.dpr,2);assert.equal(report.errors.length,0);if(workload==='stream')assert(report.streamTicksIncludingWarmup>=24);if(workload==='webgl')assert(report.workUnitsIncludingWarmup>0);console.log(workload,'browser workload completed; not a Gecko or Pixel benchmark');await page.close();}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});''')
print('Materialised six distinct workloads, safe local reports and browser execution tests.')
